# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: buildandtest
  pool:
    vmImage: windows-latest # works for ubuntu 
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: drop
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
      appType: 'webAppLinux'
      appName: 'oct27my-app-dotnet'
      deployToSlotOrASE: true
      resourceGroupName: 'oct27-myapp-rg'
      slotName: 'staging'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

- job: deploy
  dependsOn: buildandtest
  pool: 
    vmImage: ubuntu-latest  
  steps:
  - download: current
    artifact: drop
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
      appType: 'webAppLinux'
      appName: 'oct27my-app-dotnet'
      resourceGroupName: 'oct27-myapp-rg'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
