# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

parameters:
  - name: resourceIds
    type: string
    values:
    - /subscriptions/<obfuscated>/resourceGroups/<obfuscated>/providers/Microsoft.Network/loadBalancers/kubernetes-internal
    - /subscriptions/<obfuscated>/resourceGroups/<obfuscated>/providers/Microsoft.Network/loadBalancers/kubernetes
    - /subscriptions/<obfuscated>/resourceGroups/<obfuscated>/providers/Microsoft.Network/loadBalancers/kubernetes-deploy
  - name: environments
    type: string
    values: 
    - prod1
    - prod2
    - prod3

jobs:
 
- ${{ each resourceId in parameters.resourceIds }}:

  - ${{ each env in split(parameters.environments, ',')}}:

    - job: ${{ replace(split(resourceId, '/')[8], '-', '_') }}_${{ env }}
      
      steps:  
            - script: echo "Output"


# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# jobs:
# - job: 'Test'
#   pool:
#     vmImage: 'ubuntu-latest' # other options: 'macOS-latest', 'windows-latest'
#   strategy:
#     matrix:
#       Python38:
#         python.version: '3.8'
#       Python39:
#         python.version: '3.9'
#       Python310:
#         python.version: '3.10'

#   steps:
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '$(python.version)'
# variables:
#   buildConfiguration: 'Release'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
