trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
- task: DotNetCoreCLI@2
  displayName: 'Install dotnetsay'
  inputs:
    command: custom
    custom: tool
    arguments: 'install -g dotnetsay'


# stages:
# - stage: 'Build'
#   displayName: 'Build the web application'
#   jobs: 
#   - job: 'Build'
#     displayName: 'Build job'
#     pool:
#       vmImage: 'ubuntu-20.04'
#       demands:
#       - npm

#     variables:
#       wwwrootDir: 'wwwroot'
#       dotnetSdkVersion: '6.x'

#     steps:
#     - task: UseDotNet@2
#       displayName: 'Use .NET SDK $(dotnetSdkVersion)'
#       inputs:
#         version: '$(dotnetSdkVersion)'



# trigger:
# - master

# variables:
#   buildConfiguration: 'Release'

# jobs:
# - job: Build
#   pool:
#     vmImage: windows-latest
#   steps:
#   - task: DotNetCoreCLI@2
#     inputs:
#       command: publish
#       publishWebProjects: True
#       arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#       zipAfterPublish: True
#   - task: PublishPipelineArtifact@1
#     inputs:
#       targetPath: '$(Build.ArtifactStagingDirectory)' 
#       artifactName: drop
#   # - task: AzureWebApp@1
#   #   inputs:
#   #     azureSubscription: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
#   #     appType: 'webAppLinux'
#   #     appName: 'oct27my-app-dotnet'
#   #     deployToSlotOrASE: true
#   #     resourceGroupName: 'oct27-myapp-rg'
#   #     slotName: 'staging'
#   #     package: '$(Build.ArtifactStagingDirectory)/**/*.zip'

# - job: Deploy
#   dependsOn: Build
#   pool: 
#     vmImage: windows-latest  
  
#   steps:
#   - task: DownloadPipelineArtifact@2
#     inputs:
#       buildType: 'current'
#       artifactName: 'drop'
#       targetPath: '$(Pipeline.Workspace)'
#   # - task: AzureWebApp@1
#   #   inputs:
#   #     azureSubscription: 'DevOps Pipelines - ARM Horizontal Work(82c135d4-f813-4bec-a93e-60e4323918ee)'
#   #     appType: 'webAppLinux'
#   #     appName: 'oct27my-app-dotnet'
#   #     resourceGroupName: 'oct27-myapp-rg'
#   #     package: '$(Pipeline.Workspace)/**/*.zip'